# Generated by Django 5.0.6 on 2024-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0005_customuser_login_attempts_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
