# Generated by Django 5.0.6 on 2024-06-10 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0006_customuser_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
