# Generated by Django 5.0.6 on 2024-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0007_customuser_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
